[phases.setup]
nixPkgs = ["php82"]

[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo", "php82Extensions.pdo_mysql"]

[build]
builder = "NIXPACKS"

[nixpacks]
plan = { providers = ["php"] }

[start]
cmd = "php -S 0.0.0.0:${PORT:-8080} -t ."